name: Appium Android Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  android-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install Appium
        run: |
          npm install -g appium
          appium driver install uiautomator2
          appium driver list --installed

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ runner.os }}-api-29

      - name: Run Appium tests on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: default
          arch: x86_64
          profile: pixel
          disable-animations: true
          force-avd-creation: true
          emulator-options: >-
            -no-window
            -gpu swiftshader_indirect
            -noaudio
            -no-boot-anim
            -camera-back none
            -camera-front none
          script: |
            adb wait-for-device
            sleep 30
            adb shell am force-stop com.android.settings || true
            adb shell am force-stop com.google.android.permissioncontroller || true
            appium --log-level info &
            sleep 20
            mvn -B test
      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: failure-screenshots
          path: target/screenshots/**
          if-no-files-found: ignore
